### ISSUE TITLE
duplicate and incorrect values for bf:mainTitle property query

### ISSUE THREAD

**Issue by kallimathios** [LD4P/graph-explorer#5]
I have been experimenting with querying resources and filtering by language tag in the Graph Explorer which has been handy for reviewing Sinopia data across environments. I've encountered some puzzling results where duplicate values are presented that do not match the RDF for the resource. Two examples are below, as well as the queries I've used. I thought there might be an issue with my query or with users entering the wrong language code (this does happen), but some are entered correctly and still display unusually. I'm not sure whether or not a transliterated title would use an "en" tag but that seems to be a common practice. The examples below were run with the Production environment and the All groups options.

query 
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX sinopia: <http://sinopia.io/vocabulary/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?subject ?main_title ?subtitle ?responsibility 
WHERE {
 ?subject a bf:Instance .
 ?subject bf:title ?title .
 ?title bf:mainTitle ?main_title .
 FILTER (LANG(?main_title) = "en")  
 ?subject bf:title ?sub_title .
 ?sub_title bf:subtitle ?subtitle .
 ?subject bf:responsibilityStatement ?responsibility .
}

Example 1:
Sinopia resource https://api.sinopia.io/resource/3cb41afb-d5a2-4342-bc8e-f8bdef2be9e4
Relevant RDF screenshot
<img width="882" alt="Screenshot 2024-03-04 at 12 57 08 PM" src="https://github.com/LD4P/graph-explorer/assets/147437673/7ec42479-16c9-4e7f-b4e0-81a44bbd15a4">

JSON extract from graph explorer query return, where line 2 should be a Chinese title and has a "zh" language tag (and excluded from the return all together); however, both values contain the contents of the value associated with the "en" language tag. Why does it retrieve both and display only the requested value?
<img width="1377" alt="Screenshot 2024-03-04 at 2 11 44 PM" src="https://github.com/LD4P/graph-explorer/assets/147437673/2e9230df-6a7c-4f63-8021-b948429c5a17">

It also does the inverse. When I change my query to:
PREFIX bf: <http://id.loc.gov/ontologies/bibframe/>
PREFIX sinopia: <http://sinopia.io/vocabulary/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT ?subject ?main_title ?subtitle ?responsibility 
WHERE {
 ?subject a bf:Instance .
 ?subject bf:title ?title .
 ?title bf:mainTitle ?main_title .
 FILTER (LANG(?main_title) = "zh")  
 ?subject bf:title ?sub_title .
 ?sub_title bf:subtitle ?subtitle .
 ?subject bf:responsibilityStatement ?responsibility .
}

I receive two results for bf:mainTitle as if both were tagged "zh"; however, only one of them would be a match.
<img width="669" alt="Screenshot 2024-03-04 at 2 14 37 PM" src="https://github.com/LD4P/graph-explorer/assets/147437673/778efbeb-efc5-4405-b864-b867f3b18ec7">

Additional examples:
Sinopia resource https://api.sinopia.io/resource/0fc8c2d8-5cb0-4b15-afff-8e4a8ec118b4 ("kor" Korean language tag, and "en" language tag for transliteration)

Sinopia resource https://api.sinopia.io/resource/42a54441-6fe1-4c5b-a547-2044a075b4aa ("ar-Arab" Arabic language tag, and "en" language tag for transliteration)

**Comment by kallimathios** [comment]
Thank you, @jermnelson ! I will use the revised query and spend some time reviewing this. I appreciate your help!

**Comment by jermnelson** [comment]
Glad to help! I'm going to close this issue.

**Comment by kallimathios** [comment]
Hi again, @jermnelson - I ran this query through the explorer but still see multiple values for the same title appearing in some (though much fewer) cases. 

In the case where we have more than one set of bf:subtitle and bf:mainTitle properties being used with bf:Title and another BF class like Parallel Title or Variant Title, I believe it will continue to pull in both values. This is because bf:Title is defined as the blank node through a wild card, which is defined as having a bf:mainTitle and bf:subtitle property, which in this case could include bf:ParallelTitle. My example resource is in Stage: https://api.stage.sinopia.io/resource/58d31f37-c94f-491d-b1d9-791344180703
<img width="880" alt="Screenshot 2024-03-06 at 10 38 11 AM" src="https://github.com/LD4P/graph-explorer/assets/147437673/d791a833-01c8-4c15-aaf0-a9d5338b9184">


I will keep working on this query because it may pose issues with the title mapping for Sinopia to FOLIO Instances. Thank you, again!

**Comment by jermnelson** [comment]
@kallimathios, I am not sure that the issue is because of how the ?title blank node is selected. In the above example  for https://api.stage.sinopia.io/resource/58d31f37-c94f-491d-b1d9-791344180703, the title and subtitle are both correct for the `_:b66` blank node. To confirm that the same ?title blank node is used for both rows, if you add `?title` to your SELECT clause `SELECT ?subject ?title ?main_title ?subtitle ?responsibility`, you can see the ?title blank node is `https://api.stage.sinopia.io/resource/58d31f37-c94f-491d-b1d9-791344180703#b66`.

The duplication is occurring because there are two `bf:responsibilityStatement` objects for this resource with each object being displayed as separate lines above. Here is the JSON-LD for `bf:responsibilityStatement` for this resource:
```
 "http://id.loc.gov/ontologies/bibframe/responsibilityStatement": [
        {
          "@value": " マテウシュ・ウルバノヴィチ  著 ; サイドランチ 編",
          "@language": "ja-Jpan"
        },
        {
          "@value": "Mateushu Urubanovichi cho ; Saidoranchi hen",
          "@language": "ja-Latn"
        }
      ],
```

**Comment by kallimathios** [comment]
Ah, I see. Thank you so much!
